title: "Yindong Hua - Research Assistant"
description: "Personal website and resume of Yindong Hua, Research Assistant at Stony Brook University."
baseurl: ""         # For user/organization sites, leave this empty.
url: "https://lindonhua9.github.io"

