title: "Yindong Hua - Research Assistant"
description: "Online CV and personal website of Yindong Hua, Research Assistant at Stony Brook University."
baseurl: ""   # For a GitHub user site, leave this empty; for a project site, set this to "/your-repo-name"
url: "https://lindonhua9.github.io"

profile:
  name: "Yindong Hua"
  role: "Research Assistant"
  email: "yindong.hua@stonybrook.edu"
  phone: "631-820-5091"
  address: "8 Hirsch Ave, Coram, NY, 11727"

social:
  linkedin: "https://www.linkedin.com/in/yindong-hua-b85456bb/"
  github: "https://github.com/lindonhua9"
  twitter: "https://twitter.com/your-twitter-handle"

education:
  - degree: "Ph.D. in Computer Engineering"
    institution: "Stony Brook University"
    period: "01/2020 - 12/2025"
  - degree: "Master of Electrical Engineering"
    institution: "Peking University"
    period: "09/2013 - 07/2016"
  - degree: "Bachelor of Electrical Engineering"
    institution: "Henan University"
    period: "09/2009 - 07/2013"

